-- MySQL Script generated by MySQL Workbench
-- dom 22 mai 2022 22:59:22
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema MyVideo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MyVideo` ;

-- -----------------------------------------------------
-- Schema MyVideo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MyVideo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `MyVideo` ;

-- -----------------------------------------------------
-- Table `MyVideo`.`Videos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyVideo`.`Videos` ;

CREATE TABLE IF NOT EXISTS `MyVideo`.`Videos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(200) NOT NULL,
  `url` VARCHAR(100) NOT NULL,
  `titulo` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_croatian_ci;


-- -----------------------------------------------------
-- Table `MyVideo`.`Tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyVideo`.`Tags` ;

CREATE TABLE IF NOT EXISTS `MyVideo`.`Tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `MyVideo`.`TagPorVideo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MyVideo`.`TagPorVideo` ;

CREATE TABLE IF NOT EXISTS `MyVideo`.`TagPorVideo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_video` INT NOT NULL,
  `id_tag` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `TagPorVideo_FK` (`id_video` ASC) VISIBLE,
  INDEX `TagPorVideo_FK_1` (`id_tag` ASC) VISIBLE,
  CONSTRAINT `TagPorVideo_FK`
    FOREIGN KEY (`id_video`)
    REFERENCES `MyVideo`.`Videos` (`id`),
  CONSTRAINT `TagPorVideo_FK_1`
    FOREIGN KEY (`id_tag`)
    REFERENCES `MyVideo`.`Tags` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
